import { TrendingRio } from '@/lib/dbActions';

const fallbackTrendingRios: TrendingRio[] = [
  { id: 1,
    name: 'Ka Mea Kolo',
    blurb: "Shares enthusiasm for Earth's diverse creatures, especially those that call Hawai'i home.",
    count: 0,
  },
  { id: 2,
    name: 'Women in STEM',
    blurb: 'Support, , and elevate students who identify as women pursuing degrees in STEM.',
    count: 0,
  },
  { id: 3,
    name: 'Natural Sciences Student Ambassadors',
    blurb: 'Promote a welcoming and inclusive community for all students pursuing a degree in the Natural Sciences',
    count: 0,
  },
  { id: 4,
    name: 'K-pop Cardio Crew ',
    blurb: 'Creating a supportive community for students who love K-Pop and dancing.',
    count: 0,
  },
  { id: 5,
    name: 'Beta Beta Gamma Sorority',
    blurb: 'Cultivate lifelong friendships, celebrate diversity, and make meaningful contributions to society.',
    count: 0,
  },
  { id: 6,
    name: 'Cafe Hoppers',
    blurb: 'We also explore and engage with small businesses owners within our community.',
    count: 0,
  },
  { id: 7,
    name: 'Chinese Club',
    blurb: 'Create a community to learn, appreciate, and celebrate aspects of Chinese culture and language.',
    count: 0,
  },
  { id: 8,
    name: 'Hawaii Powerlifting Club',
    blurb: 'Create a team that can represent the University at local,  state, and national competitions.',
    count: 0,
  },
  { id: 9,
    name: 'Inspire Church YA',
    // eslint-disable-next-line max-len
    blurb: 'Provide a Christ- community where students can grow in their faith and build relationships. asdfasdfasd fasdfasdfasdfas dfasdfa sdfasdfas dfasdfasdfa sdfasdfasd asdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdf',
    count: 0,
  },
  { id: 10,
    name: 'Inspire Church asdfaYA',
    blurb: 'Provide a Christ- community where students can grow in their faith and build relationships.',
    count: 0,
  },
];

export default fallbackTrendingRios;
